SEND_SLACK="YES"
SLACK_WEBHOOK_URL="https://hooks.slack.com/services/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"
DEFAULT_RECIPIENT_SLACK="todo-monitoring-pharmacy"

SEND_EMAIL="YES"
DEFAULT_RECIPIENT_EMAIL="josegregoriocoronelcolombo@gmail.com jflores@unis.edu.gt"

# (recomendado: destinatarios por rol)
role_recipients_slack[sysadmin]="todo-monitoring-pharmacy"
role_recipients_email[sysadmin]="josegregoriocoronelcolombo@gmail.com jflores@unis.edu.gt"
