# ./netdata/config/health.d/backend.conf

alarm: backend_cpu_high
on: cgroup_cpu
lookup: average -5m unaligned of user,system
units: %
every: 30s
warn: $this > 2
crit: $this > 5
for: 1m
families: backend-prod-pharmacy
to: sysadmin

alarm: backend_mem_high
on: cgroup_mem
lookup: average -5m unaligned of used
units: MiB
every: 1m
warn: $this > 5
crit: $this > 50
for: 5m
families: backend-prod-pharmacy
to: sysadmin

alarm: backend_net_high
on: cgroup_net
lookup: average -5m unaligned of received, sent
units: bytes/s
every: 1m
warn: $this > 10000000
crit: $this > 20000000
families: backend-prod-pharmacy
to: sysadmin

alarm: backend_no_net
on: cgroup_net
lookup: min -10m unaligned of received, sent
units: bytes/s
every: 1m
warn: $this = 0
for: 10m
families: backend-prod-pharmacy
to: sysadmin
